X = Y = 50

MAX_ANIMALS_PER_HELPER = 4
MAX_SIGHT_KM = 5
MAX_DISTANCE_KM = 1
MAX_FLOCK_SIZE = 4
ANIMAL_MOVE_PROBABILITY = 0.5

# MIN_T = 2016
MIN_T = 16
MAX_T = MIN_T * 2
START_RAIN = MIN_T / 2

ONE_BYTE = 1 << 8
